// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceObject.EF;

#nullable disable

namespace SpaceObject.Migrations
{
    [DbContext(typeof(SpaceObjectContext))]
    [Migration("20241103132921_SpaceObjects_01")]
    partial class SpaceObjects_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceObject.Entities.AsteroidItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("asteroid_items", (string)null);
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidProperty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idAsteroidItem")
                        .HasColumnType("int")
                        .HasColumnName("FK_isAsteroidItem");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<float>("speed")
                        .HasColumnType("real");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("idAsteroidItem")
                        .IsUnique()
                        .HasDatabaseName("IX_AsteroidProperty_idAsteroidItem");

                    b.ToTable("asteroid_properties", (string)null);
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidProperty", b =>
                {
                    b.HasOne("SpaceObject.Entities.AsteroidItem", "asteroidItem")
                        .WithOne("asteroidProperty")
                        .HasForeignKey("SpaceObject.Entities.AsteroidProperty", "idAsteroidItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asteroidItem");
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidItem", b =>
                {
                    b.Navigation("asteroidProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
