// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceObject.EF;

#nullable disable

namespace SpaceObject.Migrations
{
    [DbContext(typeof(SpaceObjectContext))]
    partial class SpaceObjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceObject.Entities.AsteroidImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idAsteroidItem")
                        .HasColumnType("int")
                        .HasColumnName("FK_IdAsteroidItem");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idAsteroidItem")
                        .IsUnique()
                        .HasDatabaseName("IX_AsteroidImage_idAsteroidItem");

                    b.ToTable("asteroid_images", (string)null);
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("asteroid_items", (string)null);
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidProperty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idAsteroidItem")
                        .HasColumnType("int")
                        .HasColumnName("FK_IdAsteroidItem");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<float>("speed")
                        .HasColumnType("real");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("idAsteroidItem")
                        .IsUnique()
                        .HasDatabaseName("IX_AsteroidProperty_idAsteroidItem");

                    b.ToTable("asteroid_properties", (string)null);
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidImage", b =>
                {
                    b.HasOne("SpaceObject.Entities.AsteroidItem", "asteroidItem")
                        .WithOne("asteroidImage")
                        .HasForeignKey("SpaceObject.Entities.AsteroidImage", "idAsteroidItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asteroidItem");
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidProperty", b =>
                {
                    b.HasOne("SpaceObject.Entities.AsteroidItem", "asteroidItem")
                        .WithOne("asteroidProperty")
                        .HasForeignKey("SpaceObject.Entities.AsteroidProperty", "idAsteroidItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asteroidItem");
                });

            modelBuilder.Entity("SpaceObject.Entities.AsteroidItem", b =>
                {
                    b.Navigation("asteroidImage");

                    b.Navigation("asteroidProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
